### ISSUE TITLE
Bug fix - Stop running over elderly people

### ISSUE THREAD

**Issue by ak2466** [hberger1119/cs386-a2.1#1]
Not running over elderly people might help us convince regulators to push our software to vehicles on the market sooner.

**Comment by rhallk01** [comment]
I think this is a good feature and should be refined but not be fixed.

**Comment by ak2466** [comment]
> I think this is a good feature and should be refined but not be fixed.

Very fair. Some elderly people are a nuisance anyways. Do you think this is a bug or a feature? @hberger1119

**Comment by hberger1119** [comment]
Resolved!
